import Head from 'next/head'
import { Inter } from 'next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,AiFillLinkedin,AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Soumya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 '>
       <section className='  min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons'>
            aymuos
          </h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill className=' cursor-pointer text-2xl'/>
            </li>
            <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
          </ul>
        </nav>
        <div className='text-center p-10 py-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium' >
            Soumya Mukherjee
          </h2>
          <h3 className='text-2xl py-2'>
            Full Stack Developer
          </h3>
          <p className='text-md py-5 leading-8 text-grey-800'> Crafting dynamic digital experiences with the power of Java and React - bringing your ideas to life from front-end to back-end.</p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-grey-600'> 
          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillGithub />
          </div>
        <div className='relative bg-gradient-to-b from-teal-300 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden'>
          <Image src={deved} layout="fill" objectFit='cover'/>
        </div>
       </section>

       
       <section>
        <div>
          <h3 className='text-3xl py-1'> Technology I work on :</h3>
          <p className='text-md py-2 leading-8 text-gray-600'>
          <ul className='list-disc'>As a Java Full Stack Developer, I have experience working with a variety of technologies in both the front-end and back-end. Some of the key technologies I work with include:</ul>
        <ul>
          <li> <span className= 'text-gray-700 font-bold'>Java </span>: I have a strong foundation in core Java concepts, including object-oriented programming, data structures, algorithms, and design patterns. I use Java to develop web applications, APIs, and microservices.</li>

          <li><span className= 'text-gray-700 font-bold'>Spring Framework </span>: I work extensively with the Spring Framework, including Spring Boot, Spring MVC, and Spring Data JPA. I use Spring to build scalable, modular, and maintainable web applications.</li>

          <li><span className= 'text-gray-700 font-bold'>JavaScript</span>: I have experience with various JavaScript frameworks, including Angular, React, and Vue. I use JavaScript to create interactive user interfaces and to handle client-side logic.</li>

          <li><span className= 'text-gray-700 font-bold'>HTML/CSS </span> : I have a solid understanding of HTML and CSS, and I use these technologies to create responsive and visually appealing web pages.</li>

          <li><span className= 'text-gray-700 font-bold'> Relational Databases </span> : I have experience working with relational databases like MySQL, Oracle, and PostgreSQL. I use SQL to write complex queries and manage database transactions.</li>

          <li><span className= 'text-gray-700 font-bold'> NoSQL Databases </span> : I also work with NoSQL databases like MongoDB and Cassandra. I use these databases to store unstructured data and to build scalable and high-performance applications.</li>

          <li><span className= 'text-gray-700 font-bold'> RESTful APIs </span>: I have  experience building RESTful APIs using technologies like Spring Boot and Jersey. I use these APIs to enable communication between different parts of an application.</li>

          <li><span className= 'text-gray-700 font-bold'> DevOps </span> : I have experience with tools like Git, Jenkins, Docker, and Kubernetes. I use these tools to automate the development, testing, and deployment of applications.</li>

          Overall, I am a versatile Full Stack Developer with a strong focus on Java technologies.

 </ul>

          </p>
          </div>
          
       </section>
      </main>
    </div>
  );
}
